# Generated by Django 5.1.3 on 2025-02-03 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_event_time_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='location',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='DUMMY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(default='DUMMY', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='DUMMY', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='current_funding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='full_description',
            field=models.TextField(default='DUMMY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='funding_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.TextField(default='DUMMY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='api.tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='api.tag'),
        ),
    ]
