# Generated by Django 5.1.3 on 2025-02-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tag_rename_venue_event_location_blog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('trxID', models.CharField(max_length=20)),
                ('ref', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
