# Generated by Django 5.1.3 on 2025-02-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_donation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donation",
            old_name="additional_info",
            new_name="add_info",
        ),
    ]
