# Generated by Django 5.1.3 on 2025-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_treasury_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='trnx_statement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treasury',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
